import { Bus, Code2, Database, Sparkles, TestTube } from "lucide-react";

const projects = [
  {
    slug: "xpath-generator",
    title: "XPath Generator",
    subtitle: "Chrome Extension",
    desc: "A Chrome Extension developed to automate XPath generation for web elements, helping QA engineers and automation testers generate reliable XPath locators quickly.",
    details: "The extension improves testing efficiency by reducing manual effort and supports multiple XPath strategies for dynamic web applications.",
    tech: ["JavaScript", "Chrome API", "XPath", "Selenium"],
    tags: ["Open Source", "Testing Tool"],
    highlights: [
      "Automated XPath generation for web elements",
      "Supports multiple XPath strategies",
      "Improved software testing efficiency",
      "Compatible with modern web applications",
      "Cross-browser XPath validation",
      "Comprehensive technical documentation",
    ],
    gradient: "linear-gradient(135deg,#8b5cf6 0%,#06b6d4 100%)",
    icon: <Code2 size={28} />,
  },
  {
    slug: "axiomyth",
    title: "Axiomyth",
    subtitle: "Automation Testing Platform",
    desc: "A no-code automation testing platform designed to simplify software testing workflows.",
    details: "Contributed to product testing, API validation, requirement analysis, UX testing, defect reporting, and Agile development processes while collaborating with cross-functional teams.",
    tech: ["No-Code", "API Testing", "Azure DevOps", "Agile"],
    tags: ["Enterprise", "Testing Platform"],
    highlights: [
      "No-code automation workflow testing",
      "API and functional testing",
      "Requirement analysis & validation",
      "UX testing and usability verification",
      "Bug reporting using Azure DevOps",
      "Agile team collaboration",
    ],
    gradient: "linear-gradient(135deg,#ec4899 0%,#8b5cf6 100%)",
    icon: <TestTube size={28} />,
  },
  {
    slug: "dynamic-web-scraper",
    title: "Dynamic Web Scraper",
    subtitle: "Python Automation & Data Extraction",
    desc: "A Python-based web scraping application designed to automate the extraction of structured data from dynamic websites.",
    details: "The scraper intelligently navigates multiple pages, handles lazy loading and infinite scrolling, collects detailed information, and exports organized datasets for analysis and reporting.",
    tech: ["Python", "Selenium", "Pandas", "OpenPyXL", "XPath", "Chrome WebDriver"],
    tags: ["Automation", "Web Scraping"],
    highlights: [
      "Automated extraction of structured web data",
      "Handles dynamic content, lazy loading & infinite scrolling",
      "Multi-page navigation with duplicate detection",
      "Robust XPath-based element identification",
      "Exports cleaned data into Excel spreadsheets",
      "Resilient architecture with comprehensive exception handling",
    ],
    gradient: "linear-gradient(135deg,#f97316 0%,#ef4444 100%)",
    icon: <Database size={28} />,
  },
  {
    slug: "neon-space-match",
    title: "Neon Space Match",
    subtitle: "Interactive Memory Matching Game",
    desc: "A responsive space-themed memory matching game built with React, Framer Motion, and Tailwind CSS.",
    details: "The game challenges players to match randomly generated celestial pairs while tracking time, moves, errors, combos, hints, progress, and scores through an animated neon interface.",
    liveUrl: "https://tanaypatil1503.github.io/neon-spacematch/",
    tech: ["React", "JavaScript", "Tailwind CSS", "Framer Motion", "Lucide React"],
    tags: ["Frontend Project", "Interactive Game"],
    highlights: [
      "Randomized 18-card celestial matching grid",
      "Animated 3D card flip and hover interactions",
      "Timer, moves, errors, progress and combo tracking",
      "Hint system with limited temporary card reveals",
      "Dynamic scoring with time, combo and move bonuses",
      "Personal best score persistence using localStorage",
    ],
    gradient: "linear-gradient(135deg,#06b6d4 0%,#7c3aed 100%)",
    icon: <Sparkles size={28} />,
  },
  {
    slug: "online-bus-ticket-booking",
    title: "Online Bus Ticket Booking System",
    subtitle: "Web-Based Booking Platform",
    desc: "A web application that digitizes the complete bus reservation process by allowing passengers to search buses, check seat availability, reserve tickets, and manage bookings.",
    details: "Administrators can efficiently manage buses, routes, schedules, fares, and booking records through a dedicated dashboard.",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    tags: ["Minor Project", "Web Application"],
    highlights: [
      "Passenger registration and secure login",
      "Real-time bus search & seat availability",
      "Online ticket booking with booking history",
      "Admin dashboard for buses, routes & schedules",
      "Booking reports and centralized database",
      "Three-tier architecture with ERD & DFD design",
    ],
    gradient: "linear-gradient(135deg,#10b981 0%,#059669 100%)",
    icon: <Bus size={28} />,
  },
];

export default projects;
